import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const root=new URL('../companion/extension/',import.meta.url);
const shared=await readFile(new URL('shared.js',root),'utf8');
const extensionId='test-extension';
const sender={id:extensionId,url:`chrome-extension://${extensionId}/desk.html`,tab:{id:7}};
let handler,requests=[];
const chrome={runtime:{id:extensionId,getURL:p=>`chrome-extension://${extensionId}/${p}`,onMessage:{addListener:f=>handler=f}}};
const png=Uint8Array.from(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jN1kAAAAASUVORK5CYII=','base64'));
const context=vm.createContext({chrome,URL,Uint8Array,Blob,FormData,AbortSignal,atob,btoa,setTimeout,clearTimeout,fetch:async(url,init)=>{requests.push({url,init});return new Response(JSON.stringify({ok:true}),{headers:{'content-type':'application/json'}})}});
vm.runInContext(shared,context);const A=context.Atelier;
assert.equal(A.samePrompt('第一行\n\n第二行\n\n\n第三行','第一行\n第二行\n\n第三行'),true);
assert.equal(A.samePrompt('first\r\n\r\nsecond','first\nsecond'),true);
assert.equal(A.samePrompt('保留白色围挡','修改白色围挡'),false);
assert.equal(A.samePrompt('只改右侧\n保持背景','只改右侧'),false);
assert.equal(A.samePrompt('A B','AB'),false);
assert.equal(A.trusted(sender),true);
assert.equal(A.trusted({...sender,url:'https://chatgpt.com/'}),false);
assert.equal(A.trusted({...sender,id:'other-extension'}),false);
assert.equal(A.conversation('https://chatgpt.com/c/abc-123?x=y'),'https://chatgpt.com/c/abc-123');
assert.equal(A.conversation('https://chatgpt.com.evil.test/c/abc'),null);
assert.equal(A.conversation('https://chatgpt.com/'),null);
assert.equal(A.mime(A.bytes(Buffer.from(png).toString('base64'))),'image/png');
assert.throws(()=>A.bytes(btoa('not an image')));
assert.throws(()=>A.bytes('!invalid'));
assert.throws(()=>A.bytes('A'.repeat(15*1024*1024)));
vm.runInContext(await readFile(new URL('studio.js',root),'utf8'),context);
const call=(m,s=sender)=>new Promise(resolve=>{if(handler(m,s,resolve)!==true)resolve(null)});
const worker='0a5647a5-80d4-4c4b-99e4-acb0a7c821b9';
const noImages=await call({target:'studio',action:'inputs',worker,images:[]});
assert.equal(noImages.ok,true);assert.equal(noImages.files.length,0);assert.equal(requests.length,0);
assert.equal(await call({target:'studio',action:'claim',worker},{...sender,url:'https://evil.test'}),null);
assert.equal(requests.length,0);
assert.equal((await call({target:'studio',action:'arbitrary-fetch',worker,url:'https://evil.test'})).ok,false);
assert.equal(requests.length,0);
assert.equal((await call({target:'studio',action:'inputs',worker,images:[{id:'../../private'}]})).ok,false);
assert.equal(requests.length,0);
assert.equal((await call({target:'studio',action:'heartbeat',worker,state:'ready'})).ok,true);
assert.equal(requests[0].url,'/api/companion');
assert.equal(requests[0].init.credentials,'same-origin');
assert.equal(requests[0].init.redirect,'error');
assert.equal((await call({target:'studio',action:'complete',worker,id:worker,data:Buffer.from(png).toString('base64')})).ok,true);
assert.equal(requests[1].init.body.get('file').type,'image/png');
const manifest=JSON.parse(await readFile(new URL('manifest.json',root),'utf8'));
assert.deepEqual(manifest.permissions,['storage']);assert.equal(manifest.host_permissions.length,2);
assert(!manifest.host_permissions.some(x=>x.includes('<all_urls>')||x==='https://*/*'));
console.log('PASS: extension sender isolation, exact conversation origins, image bounds/signatures, fixed same-origin endpoint, invalid request rejection, multipart result, minimal permissions. No ChatGPT generation.');
