import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
import {DatabaseSync} from 'node:sqlite';
const js=ts.transpileModule(fs.readFileSync('lib/architecture.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext}}).outputText;
const {architecturePrompt,DEFAULT_PRESERVE_RULES}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
assert.ok(architecturePrompt('修改',[]).includes(DEFAULT_PRESERVE_RULES));
const custom=architecturePrompt('水彩画',[],false,'只保留人物，背景可以重画。');
assert.ok(custom.includes('只保留人物，背景可以重画。'));
assert.ok(!custom.includes('保留原相机'));
assert.ok(!architecturePrompt('改图',[],false,'').includes(DEFAULT_PRESERVE_RULES));
const db=new DatabaseSync(':memory:');
for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())db.exec(fs.readFileSync('drizzle/'+f,'utf8'));
db.exec("INSERT INTO projects (id,name,created) VALUES ('p','test','2026')");
const sql=fs.readFileSync('app/api/workspace/route.ts','utf8').match(/db.prepare\("(UPDATE projects SET preserveRules=[^"\n]+)"\)/)[1];
assert.equal(db.prepare(sql).run('自定义','p',0).changes,1);
assert.equal(db.prepare(sql).run('过时编辑','p',0).changes,0);
assert.equal(db.prepare(sql).run('','p',1).changes,1);
assert.equal(db.prepare("SELECT preserveRules FROM projects WHERE id='p'").get().preserveRules,'');
console.log('PASS: default/custom/empty prompt rules, durable storage, conflict guard, migrations. No generation quota used.');
