import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
const db=new DatabaseSync(':memory:');
for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())db.exec(fs.readFileSync('drizzle/'+f,'utf8'));
db.exec(`INSERT INTO projects (id,name,created) VALUES ('a','人物任务','2026'),('b','建筑任务','2027');
INSERT INTO assets (id,project,name,mime,kind,created) VALUES ('aa','a','a.png','image/png','original','2026'),('bb','b','b.png','image/png','original','2027');
INSERT INTO versions (id,project,asset,prompt,created) VALUES ('a0','a','aa','人物','2026'),('b0','b','bb','建筑','2027');
INSERT INTO versions (id,project,parent,asset,prompt,created,deleted) VALUES ('a1','a','a0','aa','修改人物','2028',0),('b1','b','b0','bb','已删除','2029',1);`);
const source=fs.readFileSync('app/api/workspace/route.ts','utf8');
const query=source.match(/db.prepare\("(SELECT p\.\*[^"\n]+)"\)/)[1];
const result=db.prepare(query).all();
assert.equal(result.length,2);
assert.equal(result.find(p=>p.id==='a').versionCount,2);
assert.equal(result.find(p=>p.id==='b').versionCount,1);
assert.equal(result.find(p=>p.id==='a').thumbnail,'aa');
assert.equal(result.find(p=>p.id==='b').thumbnail,'bb');
assert.deepEqual(db.prepare('SELECT id FROM versions WHERE project=? ORDER BY created,id').all('a').map(v=>v.id),['a0','a1']);
console.log('PASS: independent tasks, scoped history, per-task thumbnails/counts, deleted-version exclusion.');
const deleteSql=source.match(/db.prepare\("(UPDATE projects SET deleted=[^"\n]+)"\)/)[1];
assert.equal(db.prepare(deleteSql).run(1,'a','a').changes,1);
assert.equal(db.prepare("SELECT deleted FROM projects WHERE id='a'").get().deleted,1);
assert.equal(db.prepare("SELECT deleted FROM projects WHERE id='b'").get().deleted,0);
assert.equal(db.prepare('SELECT COUNT(*) AS n FROM versions').get().n,4);
assert.equal(db.prepare(deleteSql).run(0,'a','a').changes,1);
db.exec(`INSERT INTO edit_jobs (id,project,parent,prompt,"references",model,status,created,updated) VALUES ('j','a','a1','','[]','chatgpt-web','running','2026','2026')`);
assert.equal(db.prepare(deleteSql).run(1,'a','a').changes,0);
assert.equal(db.prepare(deleteSql).run(1,'b','b').changes,1);
console.log('PASS: task deletion/restoration, intact histories, other-task isolation, active-task guard.');
