import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
const db=new DatabaseSync(':memory:');
for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())db.exec(fs.readFileSync('drizzle/'+file,'utf8'));
db.exec(`INSERT INTO projects (id,name,prompt,revision,created) VALUES ('p','test','',0,'2026');
INSERT INTO assets VALUES ('a','p','test','image/png','original','材质','2026');
INSERT INTO versions (id,project,parent,asset,prompt,created) VALUES ('v0','p',NULL,'a','','2026'),('v1','p','v0','a','','2027'),('v2','p','v1','a','','2028');`);
const source=fs.readFileSync('app/api/workspace/route.ts','utf8');
const sql=source.match(/db.prepare\("(UPDATE versions SET deleted=\?[^"\n]+)"\)/)[1];
const change=(id,deleted,project='p')=>db.prepare(sql).run(deleted,id,project,project,deleted,project).changes;
assert.equal(change('v1',1),1);
assert.equal(db.prepare("SELECT parent FROM versions WHERE id='v2'").get().parent,'v1');
assert.equal(change('v0',1),1);
assert.equal(change('v2',1),0,'last visible version retained');
assert.equal(change('v1',0),1);
assert.equal(change('v1',1,'another-project'),0);
db.exec(`INSERT INTO edit_jobs (id,project,parent,prompt,"references",model,status,created,updated) VALUES ('j','p','v2','','[]','chatgpt-web','running','2026','2026')`);
assert.equal(change('v1',1),0,'running task blocks delete');
assert.equal(change('v0',0),0,'running task blocks restore');
assert.equal(db.prepare('SELECT COUNT(*) AS n FROM assets').get().n,1);
console.log('PASS: migrations, soft deletion, restoration, parent preservation, project isolation, last-version and active-task guards.');
