"use client";
import { useState,useEffect,useRef } from "react";
import { Upload,Layers3,LockKeyhole,ArrowUpRight,Plus,ImagePlus,Download,Save,ChevronLeft,LoaderCircle,Trash2,RotateCcw,Sparkles } from "lucide-react";
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { Slider } from "@/components/ui/slider";
import { Tabs,TabsList,TabsTrigger,TabsContent } from "@/components/ui/tabs";
import { architecturePrompt,creationPrompt,MAX_REFERENCES,MAX_PROMPT_CHARS,DEFAULT_PRESERVE_RULES } from "@/lib/architecture";
type Project={deleted:number;thumbnail?:string;versionCount?:number;created?:string;preserveRules:string|null;id:string;name:string;prompt:string;revision:number};
type Asset={id:string;name:string;kind:string;role:string};
type Version={deleted:number;id:string;parent:string|null;asset:string;prompt:string;created:string;references:string};
type Workspace={projects:Project[];project:Project|null;assets:Asset[];versions:Version[];aiReady:boolean;model:string;workerState?:string};
const roles=["材质","构造方式","建筑模型","帷幔","氛围","人群","景观","家具","其他"];
const imageUrl=(id:string)=>`/api/image/${id}`;
export default function Home(){
 const [data,setData]=useState<Workspace>({projects:[],project:null,assets:[],versions:[],aiReady:false,model:""}),[current,setCurrent]=useState(""),[prompt,setPrompt]=useState(""),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[message,setMessage]=useState(""),[split,setSplit]=useState(50),[mode,setMode]=useState("image");
 const [selectedRefs,setSelectedRefs]=useState<string[]>([]),[jobId,setJobId]=useState<string|null>(null);
 const [promptBaseline,setPromptBaseline]=useState("");
 const [preserveRules,setPreserveRules]=useState(DEFAULT_PRESERVE_RULES);
 const [showDeletedTasks,setShowDeletedTasks]=useState(false);
 const [showDeleted,setShowDeleted]=useState(false);
 const [jobInfo,setJobInfo]=useState<{phase:string;conversation?:string|null}>({phase:""});
 const refInput=useRef<HTMLInputElement>(null),mainInput=useRef<HTMLInputElement>(null),resultInput=useRef<HTMLInputElement>(null);
 const version=data.versions.find(v=>v.id===current),parent=data.versions.find(v=>v.id===version?.parent),references=current?data.assets.filter(a=>a.kind==="reference"):[],rulesDirty=!!data.project&&preserveRules!==(data.project.preserveRules??DEFAULT_PRESERVE_RULES),dirty=!!data.project&&(prompt!==promptBaseline||rulesDirty);
 const motionScene=useRef("");
 useEffect(()=>{
 const scene=[data.project?.id||"home",current,mode].join(":");
 if(motionScene.current===scene)return;const previous=motionScene.current;motionScene.current=scene;
 if(!previous||window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;
 const animations=Array.from(document.querySelectorAll(".canvas-panel,.controls")).map((el,i)=>el.animate([{opacity:.35,transform:"translateY(14px) scale(.99)"},{opacity:1,transform:"translateY(0) scale(1)"}],{duration:540,delay:i*55,easing:"cubic-bezier(.22,1,.36,1)"}));
 return()=>animations.forEach(a=>a.cancel());
 },[data.project?.id,current,mode]);
 const revealed=useRef(new WeakSet<Element>());
 useEffect(()=>{
 if(window.matchMedia("(prefers-reduced-motion: reduce)").matches||!("IntersectionObserver" in window))return;
 const animations:Animation[]=[];
 const observer=new IntersectionObserver(entries=>{let index=0;for(const entry of entries){if(!entry.isIntersecting||revealed.current.has(entry.target))continue;revealed.current.add(entry.target);observer.unobserve(entry.target);animations.push(entry.target.animate([{opacity:0,transform:"translateY(24px)"},{opacity:1,transform:"translateY(0)"}],{duration:650,delay:Math.min(index++*65,195),easing:"cubic-bezier(.22,1,.36,1)",fill:"backwards"}));}},{threshold:.08});
 document.querySelectorAll(".history,.task-card-wrap").forEach(el=>{if(!revealed.current.has(el))observer.observe(el)});
 const preference=window.matchMedia("(prefers-reduced-motion: reduce)");const stop=()=>{if(preference.matches){observer.disconnect();animations.forEach(a=>a.cancel())}};preference.addEventListener("change",stop);
 return()=>{observer.disconnect();animations.forEach(a=>a.cancel());preference.removeEventListener("change",stop)};
 },[data.projects,data.project?.id,showDeletedTasks]);
 async function api(url:string,init?:RequestInit){const r=await fetch(url,init);const d=await r.json() as any;if(!r.ok)throw Object.assign(new Error(d.error||"操作失败，请稍后重试。"),{status:r.status});return d;}
 async function load(project?:string,selected?:string,keepPrompt=false,blank=false){const d=await api(`/api/workspace${project?`?project=${encodeURIComponent(project)}`:""}`) as Workspace;if(blank){d.project=null;d.assets=[];d.versions=[];}setData(d);if(!keepPrompt)setSelectedRefs(blank?[]:d.assets.filter(a=>a.kind==="reference").slice(0,MAX_REFERENCES).map(a=>a.id));setCurrent(blank?"":d.versions.find(v=>v.id===selected&&!v.deleted)?.id||d.versions.filter(v=>!v.deleted).at(-1)?.id||"");if(!keepPrompt){setPrompt(blank?"":d.project?.prompt||"");setPromptBaseline(blank?"":d.project?.prompt||"");setPreserveRules(d.project?.preserveRules??DEFAULT_PRESERVE_RULES);}setLoaded(true);return d;}
 useEffect(()=>{const pending=sessionStorage.getItem("architecture-edit-job");if(pending)setJobId(pending);load(undefined,undefined,false,true).catch(e=>{setMessage(e.message);setLoaded(true)})},[]);
 useEffect(()=>{if(!dirty)return;const fn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=""};window.addEventListener("beforeunload",fn);return()=>window.removeEventListener("beforeunload",fn)},[dirty]);
 async function run(action:()=>Promise<void>){if(busy)return;setBusy(true);setMessage("");try{await action()}catch(e){setMessage(e instanceof Error?e.message:"操作失败，请重试。")}finally{setBusy(false)}}
 function openVersion(v:Version){if(dirty&&!window.confirm("当前有未保存的文字，切换后将放弃这些修改。继续吗？"))return;setCurrent(v.id);setMode("image");setPrompt(v.parent?v.prompt:"");setPromptBaseline(v.parent?v.prompt:"");const refs=JSON.parse(v.references||"[]") as {id:string}[];setSelectedRefs(refs.map(r=>r.id).filter(id=>data.assets.some(a=>a.id===id&&a.kind==="reference")).slice(0,MAX_REFERENCES));}
 async function newTextTask(){await run(async()=>{const id=crypto.randomUUID();await api("/api/workspace",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"createTextTask",project:id})});await load(id);setMode("image");setMessage("");});}
 async function changeTask(p:Project,deleted:boolean){
if(deleted&&!window.confirm(`删除任务“${p.name}”？它的图片和修改历程将一起收起，可在“已删除任务”中恢复。`))return;
await run(async()=>{await api("/api/workspace",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:deleted?"deleteTask":"restoreTask",project:p.id})});const clear=!data.project||(deleted&&data.project.id===p.id);await load(clear?undefined:data.project!.id,clear?undefined:current,!clear,clear);setMode("image");setMessage(deleted?"任务已删除，可在“已删除任务”中恢复。":"任务已恢复。");});
 }
 async function changeVersion(v:Version,deleted:boolean){
 if(!data.project)return;
 if(deleted&&!window.confirm(`删除 V${data.versions.indexOf(v)}？可在“已删除”中恢复，其他版本不受影响。`))return;
 await run(async()=>{await api("/api/workspace",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:deleted?"deleteVersion":"restoreVersion",project:data.project!.id,id:v.id})});await load(data.project!.id,current,true,!current);setMode("image");setMessage(deleted?"版本已删除，可在修改历程的“已删除”中恢复。":"版本已恢复。");});
 }
 async function saveRules(){if(!data.project)return;const r=await api("/api/workspace",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"preserveRules",project:data.project.id,preserveRules,revision:data.project.revision})});setData(d=>({...d,project:d.project?{...d.project,preserveRules,revision:r.revision}:null}));setMessage("保留要求已保存，后续生成将使用这段内容。");}
 async function save(){if(!data.project)return;const r=await api("/api/workspace",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"draft",project:data.project.id,prompt,revision:data.project.revision})});setData(d=>({...d,project:d.project?{...d.project,prompt,revision:r.revision}:null}));setPromptBaseline(prompt);setMessage("修改要求已保存。");}
 async function upload(files:FileList|null,kind:string){if(!files?.length)return;await run(async()=>{if(kind==="original"&&dirty)throw new Error("请先保存当前修改要求，再新建任务。");let project=data.project?.id,selected=current;if(kind!=="original"&&!project)throw new Error("请先上传主图。");let uploaded=0;try{for(const file of Array.from(files)){if(file.size>10*1024*1024)throw new Error("单张图片不能超过 10 MB。");const f=new FormData();f.set("file",file);f.set("kind",kind);f.set("project",project||"");f.set("parent",current);f.set("prompt",prompt);const r=await api("/api/workspace",{method:"POST",body:f});project=r.project;if(r.version)selected=r.version;uploaded++;}}finally{if(uploaded&&project){const fresh=await load(project,selected,kind!=="original");if(kind==="reference")setSelectedRefs(fresh.assets.filter(a=>a.kind==="reference").slice(0,MAX_REFERENCES).map(a=>a.id))}}setMessage(kind==="result"?"已导入新版本，可从这一版继续修改。":kind==="reference"?"参考图已保存。":"原图已保存，开始整理你的修改想法吧。");});}
 async function changeRole(asset:Asset,role:string){await run(async()=>{await api("/api/workspace",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"role",project:data.project?.id,id:asset.id,role})});setData(d=>({...d,assets:d.assets.map(a=>a.id===asset.id?{...a,role}:a)}))})}
  function rememberJob(id:string|null){setJobId(id);if(id)sessionStorage.setItem("architecture-edit-job",id);else sessionStorage.removeItem("architecture-edit-job")}
 async function generate(){if(!data.project||jobId)return;if(prompt.length>MAX_PROMPT_CHARS||selectedRefs.length>MAX_REFERENCES){setMessage("修改要求请控制在 2000 字以内，每轮最多使用 2 张参考图。");return;}await run(async()=>{if(rulesDirty)await saveRules();const id=crypto.randomUUID();rememberJob(id);setMessage("任务已提交，等待出图电脑处理。结果会自动保存在这里。");try{const result=await api("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,project:data.project!.id,parent:version?.id||"",prompt,preserveRules:version?preserveRules:"",references:version?selectedRefs:[]})});if(result.status==="succeeded"){await load(result.project,result.version,true);setMode("image");rememberJob(null);setMessage("新版本已保存，可继续修改或下载。")}else if(result.status!=="running"){rememberJob(null);throw new Error(result.error||"生成没有完成。")}}catch(e){if(e&&typeof e==="object"&&"status" in e&&[400,401,403,409,503].includes(Number(e.status))){rememberJob(null);throw e}setMessage((e instanceof Error?e.message:"连接中断。")+" 正在核对任务状态，不会自动重复生成。");}})}
 useEffect(()=>{if(!jobId)return;let stopped=false;let missingCount=0;let timer:ReturnType<typeof setTimeout>;async function check(){try{const r=await fetch(`/api/generate?id=${encodeURIComponent(jobId!)}`);if(r.status===404){if(++missingCount<8){timer=setTimeout(check,4000);return}if(!stopped){rememberJob(null);setMessage("未找到已提交的生成任务。请检查出图电脑的连接或错误提示后再试。")}return}if(!r.ok)throw new Error("暂时无法查询任务");let job=await r.json() as {id:string;status:string;project:string;parent:string;prompt:string;references:string;version:string;error:string;phase:string;conversation?:string|null;workerState?:string;recoverable?:boolean};if(stopped)return;setJobInfo({phase:job.phase,conversation:job.conversation});setData(d=>({...d,workerState:job.workerState}));if(job.phase==="attention")setMessage(job.error||"请在电脑上检查 ChatGPT，任务不会自动重发。");if(job.recoverable){job=await api("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:job.id,project:job.project,parent:job.parent,prompt:job.prompt,references:JSON.parse(job.references).map((a:{id:string})=>a.id)})})}if(job.status==="succeeded"){await load(job.project,job.version,true);if(!stopped){rememberJob(null);setMode("image");setMessage("生成完成，结果已保存到当前任务的修改历程。")}return}if(job.status!=="running"){rememberJob(null);setMessage(job.error||"生成未完成，请检查后再试。");return}}catch{if(!stopped)setMessage("连接暂时中断，正在查询已提交任务；不会自动重复计费生成。")}if(!stopped)timer=setTimeout(check,4000)}timer=setTimeout(check,4000);return()=>{stopped=true;clearTimeout(timer)}},[jobId]);
 useEffect(()=>{let stopped=false;async function refresh(){try{const s=await api("/api/generate");if(stopped)return;setData(d=>({...d,workerState:s.workerState}));if(s.activeJob){rememberJob(s.activeJob.id);setJobInfo(info=>({...info,phase:s.activeJob.phase}))}}catch{}}void refresh();const timer=setInterval(refresh,10000);return()=>{stopped=true;clearInterval(timer)}},[]);
 const stateRef=useRef({data,current});stateRef.current={data,current};
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:"read_architecture_workspace",title:"读取建筑工作台",description:"读取当前项目及版本信息，不修改内容。",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:unknown){if(!input||typeof input!=="object"||Array.isArray(input)||Object.keys(input).length)throw new Error("Expected an empty object");const s=stateRef.current;return{project:s.data.project?.name||null,currentVersion:s.current,versions:s.data.versions.map(v=>({id:v.id,parent:v.parent,prompt:v.prompt})),aiReady:s.data.aiReady}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
 return <main className={`studio ${busy||jobId?"is-working":""}`}><header><div className="brand"><Layers3/><b>俞总和小吴的图像生成工作站</b><span>ATELIER / 02</span></div><span className="privacy"><LockKeyhole size={15}/> 私人空间</span></header><section className="intro"><div><small>IMAGE STUDIO</small><h1>让想象，成为画面。</h1><p>从一段文字，或一张图片开始。每个想法，都有自己的空间。</p></div><span className="status">{data.aiReady?"私人图片工作室":"正在连接工作室…"}</span></section>
 <input ref={mainInput} className="hidden" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{void upload(e.target.files,"original");e.target.value=""}}/>
 <input ref={refInput} className="hidden" type="file" multiple accept="image/png,image/jpeg,image/webp" onChange={e=>{void upload(e.target.files,"reference");e.target.value=""}}/>
 <input ref={resultInput} className="hidden" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{void upload(e.target.files,"result");e.target.value=""}}/>
 <div className="projectbar"><b>{data.project?data.project.name:"新建创作任务"}</b>{data.project&&<button className="secondary" disabled={!!jobId||busy||dirty} onClick={()=>void run(async()=>{await load(undefined,undefined,false,true);setMode("image");setShowDeleted(false);})}><ChevronLeft size={16}/> 返回任务首页</button>}<button className="secondary" disabled={!!jobId||busy||dirty||!loaded} onClick={()=>mainInput.current?.click()}><ImagePlus size={16}/> 上传图片</button><button className="secondary" disabled={!!jobId||busy||dirty||!loaded} onClick={()=>void newTextTask()}><Sparkles size={16}/> 文字生成</button><span>{dirty?"当前内容尚未保存":data.project?"每轮修改保存在当前任务中":"图片修改与文字创作，各自独立保存"}</span></div>
 {message&&<div key={message} role="status" className="notice">{message}</div>}
 <div className="workgrid"><section className="canvas-panel"><div className="panel-head"><b>{version?"创作画布":data.project?"文字生成":"你的画布"}</b><span>{version?`${data.assets.find(a=>a.id===version.asset)?.kind==="generated"?"AI 生成":version.parent?"导入版本":"原始图"} · V${data.versions.indexOf(version)}`:data.project?"等待创作":"尚未上传"}</span></div>
 {version?<Tabs value={mode} onValueChange={setMode}><div className="canvas-toolbar"><TabsList><TabsTrigger value="image">当前版本</TabsTrigger><TabsTrigger value="compare" disabled={!parent}>前后对比</TabsTrigger></TabsList><a className="download" href={`${imageUrl(version.asset)}?download=1`}><Download size={16}/> 下载</a></div><TabsContent value="image"><div className="canvas"><img src={imageUrl(version.asset)} alt={`当前建筑版本 V${data.versions.indexOf(version)}`}/></div></TabsContent><TabsContent value="compare"><div className="canvas compare">{parent&&<><img src={imageUrl(parent.asset)} alt="修改前的父版本"/><img src={imageUrl(version.asset)} alt="修改后的当前版本" style={{clipPath:`inset(0 0 0 ${split}%)`}}/><div className="compare-line" style={{left:`${split}%`}}/><span className="before-label">修改前</span><span className="after-label">修改后</span></>}</div><div className="comparison-slider"><Slider aria-label="前后对比位置" value={[split]} onValueChange={v=>setSplit(v[0])} min={0} max={100} step={1}/><small>拖动分隔线，对照所选版本与它的上一版</small></div></TabsContent></Tabs>:data.project?<div className="canvas text-canvas"><Sparkles size={52}/><h2>写下想象，剩下的交给创作。</h2><p>描述主体、场景、风格和光线。无需上传图片。</p><small>生成结果会保存在当前任务中，可继续多轮修改。</small></div>:<div className="canvas"><button className="upload" disabled={!!jobId||busy||!loaded} onClick={()=>mainInput.current?.click()}><span className="upload-icon">{busy||!loaded?<LoaderCircle className="spin" size={27}/>:<Upload size={27}/>}</span><h2>{busy?"正在保存图片…":"从一张图片开始"}</h2><p>人像、产品、插画、风景，或任何灵感</p><strong>选择主图 <ArrowUpRight size={17}/></strong><small>PNG、JPG、WebP · 单张不超过 10 MB</small></button></div>}
 {version&&<div className="canvas-foot preserve-editor"><label htmlFor="preserve-rules"><LockKeyhole size={15}/> 保留要求 <span>可编辑，留空则不添加额外要求</span></label><textarea id="preserve-rules" aria-label="保留要求" value={preserveRules} maxLength={2000} disabled={!data.project||busy||!!jobId} onChange={e=>setPreserveRules(e.target.value)}/><div><small>{preserveRules.length} / 2000 字{rulesDirty?" · 尚未保存":""}</small><button className="secondary" disabled={!data.project||busy||!!jobId} onClick={()=>setPreserveRules(DEFAULT_PRESERVE_RULES)}>恢复默认</button><button className="secondary" disabled={!rulesDirty||busy||!!jobId} onClick={()=>void run(saveRules)}><Save size={14}/> 保存保留要求</button></div></div>}</section>
 <section className="controls"><div className="panel-head"><b>{version?"这次想改什么？":"你想创作什么？"}</b><span>01 / 编辑</span></div><label className="field-label" htmlFor="prompt">{version?"修改要求":"画面描述"} {version&&<span className="base-label">基于 V{data.versions.indexOf(version)}</span>}</label><textarea id="prompt" value={prompt} maxLength={6000} disabled={!!jobId||busy||!data.project} onChange={e=>setPrompt(e.target.value)} placeholder={version?"例如：把背景换成日落海边，保留人物的表情与姿态。":"例如：一只橘猫坐在窗边，午后的阳光穿过白色窗帘，温暖的胶片摄影风格。"}/><div className="prompt-actions"><span>{prompt.length} / {MAX_PROMPT_CHARS} 字（生成上限）</span><button disabled={!!jobId||!data.project||busy||prompt===promptBaseline} onClick={()=>void run(save)}><Save size={14}/> 保存要求</button></div>
 <div className="reference-title"><b>参考图片</b><span>本轮 {selectedRefs.length} / {MAX_REFERENCES} 张</span></div><div className="references">{references.map((a,i)=><div className="reference" key={a.id}><Checkbox aria-label={`本轮使用参考 ${i+1}`} checked={selectedRefs.includes(a.id)} disabled={busy||!!jobId||(!selectedRefs.includes(a.id)&&selectedRefs.length>=MAX_REFERENCES)} onCheckedChange={checked=>setSelectedRefs(ids=>checked?[...ids,a.id]:ids.filter(id=>id!==a.id))}/><img src={imageUrl(a.id)} alt={`参考 ${i+1}：${a.name}`}/><div><small title={a.name}>参考 {i+1} · {a.name}</small><Select value={a.role} disabled={!!jobId||busy} onValueChange={role=>void changeRole(a,role)}><SelectTrigger aria-label={`参考 ${i+1} 的角色`}><SelectValue/></SelectTrigger><SelectContent>{roles.map(r=><SelectItem key={r} value={r}>{r}</SelectItem>)}</SelectContent></Select></div></div>)}</div><button className="reference-add" disabled={!!jobId||busy||!version||references.length>=12} onClick={()=>refInput.current?.click()}><ImagePlus size={20}/> 添加材质、构造或氛围参考</button>
 <div className="rule"><Sparkles size={18}/><div><b>{version?"保留你在意的细节":"从想法到画面"}</b><p>{version?"画布下方可编辑保留要求，生成后可对比前后变化。":"写下主体、场景、风格与光线，让描述更具体。"}</p></div></div><button className="primary" disabled={!data.aiReady||!data.project||!prompt.trim()||prompt.length>MAX_PROMPT_CHARS||selectedRefs.length>MAX_REFERENCES||busy||!!jobId} onClick={()=>void generate()}>{jobId?(jobInfo.phase==="queued"?"等待出图电脑接单…":jobInfo.phase==="attention"?"出图端需要检查":"正在处理并保存…"):"开始生成"}</button><p className="hint">每次生成 1 张，由工作室的出图电脑处理。此设备只需保留网站页面。</p><p className="hint" role="status">{data.workerState==="ready"?"出图电脑在线，可接单":data.workerState==="login_required"?"出图电脑需要重新登录":data.workerState==="attention"?"出图电脑需要人工检查":"出图电脑离线，提交后将等待它上线"}</p><details className="connection-help"><summary>如何连接出图电脑？</summary><p>只在负责出图的电脑上安装“工作室 Chrome 接单”扩展，打开接单台并点击“开始接单”，保持 Chrome 和接单台运行。使用网站修改图片的其他设备无需安装扩展、无需打开 GPT。网站登录仍使用 ChatGPT 账号。</p></details>{jobId&&jobInfo.conversation&&<a className="connection-help" href={jobInfo.conversation} target="_blank" rel="noopener noreferrer">查看 ChatGPT 对话 ↗</a>}{jobId&&["queued","attention"].includes(jobInfo.phase)&&<button className="secondary" disabled={busy} onClick={()=>void run(async()=>{await api("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:jobId,action:"cancel",acknowledge:jobInfo.phase==="attention"})});rememberJob(null);setMessage("已结束网站等待；ChatGPT 中已开始的生成不会被撤回。")})}>{jobInfo.phase==="queued"?"取消排队":"已检查 ChatGPT，结束等待"}</button>}<div className="extra-actions"><button className="secondary" disabled={!!jobId||!version||busy} onClick={()=>resultInput.current?.click()}><Upload size={15}/> 导入修改图</button><button className="secondary" disabled={!!jobId||!prompt.trim()||!data.project||busy} onClick={()=>void run(async()=>{await navigator.clipboard.writeText(version?architecturePrompt(prompt,references.filter(a=>selectedRefs.includes(a.id)),false,preserveRules):creationPrompt(prompt));setMessage("已复制包含建筑保留规则的完整提示词。")})}>复制完整提示词</button></div>
 </section></div>{data.project&&<section className="history"><div className="panel-head"><b>当前任务 · 修改历程 <span> / {data.versions.filter(v=>!v.deleted).length} 个版本</span></b>{parent&&!parent.deleted?<button className="back" disabled={!!jobId} onClick={()=>openVersion(parent)}><ChevronLeft size={16}/> 返回上一版</button>:<span>每一个想法，都有迹可循</span>}</div>{data.versions.length?<div className="version-list">{data.versions.map((v,i)=>!v.deleted&&<div key={v.id} className="version-card"><button disabled={!!jobId||busy} className={`version ${current===v.id?"selected":""}`} onClick={()=>openVersion(v)}><img src={imageUrl(v.asset)} alt={`V${i} 缩略图`}/><b>V{i} · {data.assets.find(a=>a.id===v.asset)?.kind==="generated"?"AI 生成":v.parent?"导入修改图":"原始图"}</b><small>{v.parent?`基于 V${data.versions.findIndex(x=>x.id===v.parent)}`:"方案起点"}</small><p title={v.prompt}>{v.prompt||"未填写修改说明"}</p></button><button className="version-delete" aria-label={`删除 V${i}`} disabled={!!jobId||busy||data.versions.filter(x=>!x.deleted).length<=1} onClick={()=>void changeVersion(v,true)}><Trash2 size={14}/> 删除</button></div>)}</div>:<div className="history-empty"><Plus size={20}/> 生成或导入图片后，在这里回看每轮结果。</div>}
 {data.versions.some(v=>v.deleted)&&<div className="deleted-versions"><button className="back" aria-expanded={showDeleted} onClick={()=>setShowDeleted(!showDeleted)}>已删除（{data.versions.filter(v=>v.deleted).length}）{showDeleted?" · 收起":" · 展开"}</button>{showDeleted&&<div className="deleted-list">{data.versions.map((v,i)=>v.deleted?<div key={v.id}><img src={imageUrl(v.asset)} alt={`已删除 V${i}`}/><span>V{i}</span><button className="secondary" disabled={!!jobId||busy} onClick={()=>void changeVersion(v,false)}><RotateCcw size={14}/> 恢复</button></div>:null)}</div>}</div>}
 {version?.parent&&<div className="version-note"><b>这版的修改说明</b><p>{version.prompt||"未填写修改说明"}</p><small>保存于 {new Date(version.created).toLocaleString("zh-CN")} · 已保存当时的参考图角色</small></div>}</section>}<section className="history task-history"><div className="panel-head"><b>历史任务 <span> / {data.projects.filter(p=>!p.deleted).length} 个任务</span></b><span>每个创作独立保存，可继续多轮修改</span></div>{data.projects.some(p=>!p.deleted)?<div className="task-grid">{data.projects.filter(p=>!p.deleted).map(p=><div key={p.id} className="task-card-wrap"><button className={`task-card ${data.project?.id===p.id?"selected":""}`} disabled={!!jobId||busy||dirty} onClick={()=>void run(async()=>{await load(p.id);setMode("image");setShowDeleted(false);setMessage(`已打开任务：${p.name}`);})}>{p.thumbnail?<img src={imageUrl(p.thumbnail)} alt={`任务缩略图：${p.name}`}/>:<div className="task-placeholder"><ImagePlus/></div>}<div><b>{p.name}</b><small>{p.versionCount||0} 个已保存版本 · {p.created?new Date(p.created).toLocaleDateString("zh-CN"):""}</small><span>{data.project?.id===p.id?"正在编辑":"打开任务 →"}</span></div></button><button className="version-delete" disabled={!!jobId||busy||dirty} aria-label={`删除任务：${p.name}`} onClick={()=>void changeTask(p,true)}><Trash2 size={14}/> 删除任务</button></div>)}</div>:<div className="history-empty">还没有任务，上传图片或选择文字生成开始吧。</div>}{data.projects.some(p=>p.deleted)&&<div className="deleted-versions"><button className="back" aria-expanded={showDeletedTasks} onClick={()=>setShowDeletedTasks(!showDeletedTasks)}>已删除任务（{data.projects.filter(p=>p.deleted).length}）{showDeletedTasks?" · 收起":" · 展开"}</button>{showDeletedTasks&&<div className="deleted-list">{data.projects.filter(p=>p.deleted).map(p=><div key={p.id}>{p.thumbnail&&<img src={imageUrl(p.thumbnail)} alt={`已删除任务：${p.name}`}/>}<span>{p.name}</span><button className="secondary" disabled={!!jobId||busy||dirty} onClick={()=>void changeTask(p,false)}><RotateCcw size={14}/> 恢复任务</button></div>)}</div>}</div>}</section><footer>两个人的设计，一起慢慢打磨。</footer></main>
}




