import {WEB_MODEL,workerState} from "../jobs";
import {authorize,bucket,database,fail,limitedBody,roles,imageMime} from "../storage";
export async function GET(request:Request){try{await authorize(request);const db=database();const projects=(await db.prepare("SELECT p.*, (SELECT asset FROM versions WHERE project=p.id AND deleted=0 ORDER BY created DESC,id DESC LIMIT 1) AS thumbnail, (SELECT COUNT(*) FROM versions WHERE project=p.id AND deleted=0) AS versionCount FROM projects p ORDER BY p.created DESC,p.id DESC").all()).results;const id=new URL(request.url).searchParams.get("project")||String(projects.find(p=>!p.deleted)?.id||"");const project=projects.find(p=>p.id===id&&!p.deleted)||null;const assets=project?(await db.prepare("SELECT * FROM assets WHERE project=? ORDER BY created").bind(id).all()).results:[];const versions=project?(await db.prepare("SELECT * FROM versions WHERE project=? ORDER BY created,id").bind(id).all()).results:[];return Response.json({projects,project,assets,versions,aiReady:true,model:WEB_MODEL,workerState:await workerState()},{headers:{"Cache-Control":"no-store"}})}catch(e){return fail(e)}}
export async function POST(request:Request){try{await authorize(request);const db=database();const body=await limitedBody(request);if(request.headers.get("content-type")?.includes("application/json")){const d=await body.json() as Record<string,unknown>;if(typeof d.project!=="string")throw new Error("请选择项目。");if(d.action==="createTextTask"){
if(!/^[0-9a-f-]{36}$/i.test(d.project))throw new Error("任务编号无效。");
await db.prepare("INSERT OR IGNORE INTO projects (id,name,prompt,preserveRules,revision,created) VALUES (?,?,'','',0,?)").bind(d.project,"文字创作 · "+new Date().toISOString().slice(0,16).replace('T',' '),new Date().toISOString()).run();
return Response.json({project:d.project});
}const p=await db.prepare("SELECT * FROM projects WHERE id=?").bind(d.project).first();if(!p)throw new Error("项目不存在。");if(d.action==="deleteTask"||d.action==="restoreTask"){
const deleted=d.action==="deleteTask"?1:0;
if(p.deleted===deleted)return Response.json({ok:true});
const r=await db.prepare("UPDATE projects SET deleted=? WHERE id=? AND NOT EXISTS (SELECT 1 FROM edit_jobs WHERE project=? AND status='running')").bind(deleted,d.project,d.project).run();
if(!r.meta.changes)return Response.json({error:"该任务正在生成，请完成后再删除或恢复。"},{status:409});
return Response.json({ok:true});
}if(p.deleted)throw new Error("任务已删除，请先恢复。");if(d.action==="deleteVersion"||d.action==="restoreVersion"){
if(typeof d.id!=="string")throw new Error("请选择版本。");
const v=await db.prepare("SELECT id,deleted FROM versions WHERE id=? AND project=?").bind(d.id,d.project).first<{id:string;deleted:number}>();
if(!v)return Response.json({error:"版本不存在。"},{status:404});
const deleted=d.action==="deleteVersion"?1:0;
if(v.deleted===deleted)return Response.json({ok:true});
const result=await db.prepare("UPDATE versions SET deleted=? WHERE id=? AND project=? AND NOT EXISTS (SELECT 1 FROM edit_jobs WHERE project=? AND status='running') AND (?=0 OR (SELECT COUNT(*) FROM versions WHERE project=? AND deleted=0)>1)").bind(deleted,d.id,d.project,d.project,deleted,d.project).run();
if(!result.meta.changes)return Response.json({error:"生成任务进行中时不能删除或恢复版本；每个方案至少保留一个版本。"},{status:409});
return Response.json({ok:true});
}if(d.action==="preserveRules"){
if(typeof d.preserveRules!=="string"||d.preserveRules.length>2000||!Number.isInteger(d.revision))throw new Error("保留要求不能超过 2000 字。");
const r=await db.prepare("UPDATE projects SET preserveRules=?,revision=revision+1 WHERE id=? AND revision=?").bind(d.preserveRules,d.project,d.revision).run();
if(!r.meta.changes)return Response.json({error:"另一台设备已更新方案，请复制保留当前文字，刷新后再保存。"},{status:409});
return Response.json({revision:Number(d.revision)+1});
}if(d.action==="draft"){if(typeof d.prompt!=="string"||d.prompt.length>6000||!Number.isInteger(d.revision))throw new Error("修改要求不能超过 6000 字。");const r=await db.prepare("UPDATE projects SET prompt=?,revision=revision+1 WHERE id=? AND revision=?").bind(d.prompt,d.project,d.revision).run();if(!r.meta.changes)return Response.json({error:"另一台设备已更新要求。请复制保留当前文字，刷新后再保存。"},{status:409});return Response.json({revision:Number(d.revision)+1})}if(d.action==="role"){if(typeof d.id!=="string"||typeof d.role!=="string"||!roles.includes(d.role))throw new Error("参考图类型无效。");await db.prepare("UPDATE assets SET role=? WHERE id=? AND project=? AND kind='reference'").bind(d.role,d.id,d.project).run();return Response.json({ok:true})}throw new Error("图像服务尚未接入，请先保存修改要求。");}
const form=await body.formData();const file=form.get("file");if(!(file instanceof File)||!file.size||file.size>10*1024*1024)throw new Error("请上传一张不超过 10 MB 的图片。");const bytes=new Uint8Array(await file.arrayBuffer());const mime=imageMime(bytes);const kind=String(form.get("kind"));if(!["original","reference","result"].includes(kind))throw new Error("上传类型无效。");const now=new Date().toISOString();const id=crypto.randomUUID();let project=String(form.get("project")||"");let parent:string|null=null;let prompt="";let refs="[]";
if(kind==="original"){project=crypto.randomUUID()}else{if(!await db.prepare("SELECT id FROM projects WHERE id=? AND deleted=0").bind(project).first())throw new Error("项目不存在。");if(kind==="reference"){const count=await db.prepare("SELECT COUNT(*) AS n FROM assets WHERE project=? AND kind='reference'").bind(project).first<{n:number}>();if((count?.n||0)>=12)throw new Error("每个项目最多保存 12 张参考图。")}if(kind==="result"){parent=String(form.get("parent")||"");if(!await db.prepare("SELECT id FROM versions WHERE project=? AND id=?").bind(project,parent).first())throw new Error("请选择有效的上一版本。");prompt=String(form.get("prompt")||"");if(prompt.length>6000)throw new Error("修改要求不能超过 6000 字。");refs=JSON.stringify((await db.prepare("SELECT id,role FROM assets WHERE project=? AND kind='reference'").bind(project).all()).results)}}
const key=`images/${id}`;await bucket().put(key,bytes,{httpMetadata:{contentType:mime}});try{const sql=[];if(kind==="original")sql.push(db.prepare("INSERT INTO projects (id,name,prompt,revision,created) VALUES (?,?,'',0,?)").bind(project,file.name.replace(/\.[^.]+$/,"").slice(0,100)||"未命名方案",now));sql.push(db.prepare("INSERT INTO assets (id,project,name,mime,kind,role,created) VALUES (?,?,?,?,?,'材质',?)").bind(id,project,file.name.slice(0,150),mime,kind,now));let version:string|null=null;if(kind!=="reference"){version=crypto.randomUUID();sql.push(db.prepare('INSERT INTO versions (id,project,parent,asset,prompt,"references",created) VALUES (?,?,?,?,?,?,?)').bind(version,project,parent,id,kind==="original"?"原始建筑图":prompt,refs,now))}await db.batch(sql);return Response.json({project,version,id})}catch(e){await bucket().delete(key);throw e}
}catch(e){return fail(e)}}

